apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phpipam.fullname" . }}-web
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpipam.web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "phpipam.web.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "phpipam.web.selectorLabels" . | nindent 8 }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.web.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $pullSecrets := concat (.Values.global.imagePullSecrets | default list) (.Values.imagePullSecrets | default list) }}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- range $pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "phpipam.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.web.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: web
          image: {{ include "phpipam.web.image" . }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "phpipam.fullname" . }}-config
          env:
            - name: IPAM_DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "phpipam.secretName" . }}
                  key: {{ include "phpipam.secretPasswordKey" . }}
            {{- if .Values.app.proxy.enabled }}
            - name: PROXY_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.app.proxy.existingSecret }}{{ .Values.app.proxy.existingSecret }}{{ else }}{{ include "phpipam.secretName" . }}{{ end }}
                  key: {{ if .Values.app.proxy.existingSecret }}{{ .Values.app.proxy.existingSecretPasswordKey }}{{ else }}proxy-password{{ end }}
            {{- end }}
            {{- with .Values.web.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.persistence.logo.enabled .Values.persistence.ca.enabled .Values.web.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.persistence.logo.enabled }}
            - name: logo
              mountPath: /phpipam/css/images/logo
            {{- end }}
            {{- if .Values.persistence.ca.enabled }}
            - name: ca
              mountPath: /usr/local/share/ca-certificates
            {{- end }}
            {{- with .Values.web.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.persistence.logo.enabled .Values.persistence.ca.enabled .Values.web.extraVolumes }}
      volumes:
        {{- if .Values.persistence.logo.enabled }}
        - name: logo
          persistentVolumeClaim:
            claimName: {{ include "phpipam.logoPvcName" . }}
        {{- end }}
        {{- if .Values.persistence.ca.enabled }}
        - name: ca
          persistentVolumeClaim:
            claimName: {{ include "phpipam.caPvcName" . }}
        {{- end }}
        {{- with .Values.web.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
