{{- if and .Values.mariadb.enabled (not .Values.mariadb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mariadb-credentials" (include "phpipam.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpipam.mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | quote }}
{{- end }}
