{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-credentials" (include "phpipam.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "phpipam.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.database.password | quote }}
  {{- if .Values.app.proxy.enabled }}
  {{- if not .Values.app.proxy.existingSecret }}
  proxy-password: {{ .Values.app.proxy.password | quote }}
  {{- end }}
  {{- end }}
{{- end }}
